name: indoor_crowded_regions_frontend
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  flutter_map: ^8.0.0
  location: ^8.0.0
  latlong2: ^0.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/tiles/
    - assets/tiles/17/70115/
    - assets/tiles/17/70116/
    - assets/tiles/18/140230/
    - assets/tiles/18/140231/
    - assets/tiles/18/140232/
    - assets/tiles/19/280460/
    - assets/tiles/19/280461/
    - assets/tiles/19/280462/
    - assets/tiles/19/280463/
    - assets/tiles/19/280464/
    